---
server:
    port: 8181

---
environments:
    development:
        grails:
            serverURL: http://localhost:8181
        beans:
            classroomService:
                classroomURL: 'http://localhost:9090/classrooms'
            coordinationService:
                coordinationURL: 'http://localhost:9090/coordinations'
            employeeService:
                employeeURL: 'http://localhost:9090/employees'
            colorService:
                colorURL: 'http://localhost:9090/colors'
            copyService:
                copyURL: 'http://localhost:9090/copies'
            thirdPartyService:
              thirdPartyURL: 'http://localhost:9090/thirdparties'
    test:
        grails:
            serverURL: http://localhost:8181
        beans:
            classroomService:
                classroomURL: 'http://localhost:9090/classrooms'
            coordinationService:
                coordinationURL: 'http://localhost:9090/coordinations'
            employeeService:
                employeeURL: 'http://localhost:9090/employees'
            colorService:
                colorURL: 'http://localhost:9090/colors'
            copyService:
                copyURL: 'http://localhost:9090/copies'
            thirdPartyService:
              thirdPartyURL: 'http://localhost:9090/thirdparties'
    production:
        grails:
            serverURL: http://192.168.7.254/platform-ucc
        beans:
            classroomService:
                classroomURL: 'http://192.168.7.254/uapi/classrooms'
            coordinationService:
                coordinationURL: 'http://192.168.7.254/uapi/coordinations'
            employeeService:
                employeeURL: 'http://192.168.7.254/uapi/employees'
            colorService:
                colorURL: 'http://192.168.7.254/uapi/colors'
            copyService:
                copyURL: 'http://192.168.7.254/uapi/copies'
            thirdPartyService:
              thirdPartyURL: 'http://192.168.7.254/uapi/thirdparties'

---
hibernate:
    # format_sql: true
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

dataSource:
    pooled: true
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect

environments:
    development:
        dataSource:
            # dbCreate: update
            dbCreate: create-drop
            url: jdbc:mysql://localhost/development_platform_ucc?autoReconnect=true&useSSL=false
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost/production_platform_ucc?autoReconnect=true&useSSL=false
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
---
grails:
    profile: web
    codegen:
        defaultPackage: 'ni.edu.uccleon'
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:

    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true
